# Generated by Django 6.0.1 on 2026-01-10 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pulseira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_pulseira')),
                ('nascimento', models.DateField()),
                ('condicao_medica', models.TextField(verbose_name='Condição Médica / Alergias')),
                ('medicamentos', models.TextField(help_text='Separe os remédios por vírgula ou linha (Enter)')),
                ('responsavel_nome', models.CharField(max_length=100)),
                ('responsavel_telefone', models.CharField(max_length=20)),
                ('responsavel_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para Notificação')),
                ('aceite_termos', models.BooleanField(default=False, help_text="Ao marcar, você concorda com os <a href='/termos/' target='_blank'>Termos de Uso</a> e autoriza a exibição pública.", verbose_name='Termos de Uso')),
            ],
        ),
    ]
