# Generated by Django 6.0.1 on 2026-01-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulseira',
            name='alergias',
            field=models.TextField(blank=True, verbose_name='Alergias (Remédios/Alimentos)'),
        ),
        migrations.AddField(
            model_name='pulseira',
            name='instrucoes_abordagem',
            field=models.TextField(blank=True, help_text='Ex: Fale baixo, não toque bruscamente, ofereça água.', verbose_name='Como conversar/acalmar?'),
        ),
        migrations.AddField(
            model_name='pulseira',
            name='numero_sus_convenio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº Carteirinha SUS ou Convênio'),
        ),
        migrations.AddField(
            model_name='pulseira',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NA', 'Não sei')], default='NA', max_length=3, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='condicao_medica',
            field=models.TextField(verbose_name='Condição Médica (Doenças)'),
        ),
    ]
