# Generated by Django 6.0.1 on 2026-01-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pulseira_alergias_pulseira_instrucoes_abordagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulseira',
            name='alergias',
            field=models.TextField(blank=True, help_text="Se não houver, deixe em branco. O sistema preencherá como 'Nenhuma'.", verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='condicao_medica',
            field=models.TextField(blank=True, help_text="Se não houver, deixe em branco. O sistema preencherá como 'Nenhuma'.", verbose_name='Condição Médica (Doenças)'),
        ),
    ]
