# Generated by Django 6.0.1 on 2026-01-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pulseira_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulseira',
            name='alergias',
            field=models.TextField(blank=True, help_text='Se não houver, deixe em branco. Separe por vírgula (ex: Penicilina, Amendoim).', verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='condicao_medica',
            field=models.TextField(blank=True, help_text='Se não houver, deixe em branco. Separe por vírgula (ex: Diabetes, Hipertensão).', verbose_name='Condição Médica (Doenças)'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='medicamentos',
            field=models.TextField(blank=True, help_text='Separe os remédios por vírgula ou uma linha abaixo da outra.', verbose_name='Medicamentos em Uso'),
        ),
    ]
