# Generated by Django 6.0.1 on 2026-01-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pulseira_alergias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulseira',
            name='nome_convenio',
            field=models.CharField(blank=True, help_text='Digite o nome (e o número da carteirinha, se quiser). Ex: Unimed - 123456', max_length=100, verbose_name='Nome do Convênio'),
        ),
        migrations.AddField(
            model_name='pulseira',
            name='possui_convenio',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Possui Convênio Médico?'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='numero_sus_convenio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número do Cartão SUS'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='responsavel_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail para Notificação'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='responsavel_nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='responsavel_telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone para Contato'),
        ),
    ]
