# Generated by Django 6.0.1 on 2026-01-10 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pulseira_nome_convenio_pulseira_possui_convenio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pulseira',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='medicamentos',
            field=models.TextField(blank=True, help_text='Se não houver, deixe em branco. Separe por vírgula (ex: Lozartana, Puran).', verbose_name='Medicamentos em Uso'),
        ),
    ]
