# Generated by Django 6.0.1 on 2026-02-01 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_perfil_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('digital', 'Apenas QR Code (Digital)'), ('fisico_adesivo', 'Adesivo NFC + QR'), ('fisico_resina', 'Peça em Resina (Pulseira/Colar/Chaveiro)')], max_length=20)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='creditos_pulseira',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado')], default='pendente', max_length=20)),
                ('id_transacao', models.CharField(blank=True, max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
        ),
    ]
