# Generated by Django 6.0.1 on 2026-02-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_produto_perfil_creditos_pulseira_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.CharField(blank=True, help_text='Cole o link de uma imagem ou ícone aqui', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_transacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Pago / Aprovado'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('digital', 'Apenas QR Code (Digital)'), ('fisico', 'Produto Físico (Adesivo/Resina)')], default='fisico', max_length=20),
        ),
    ]
