# Generated by Django 6.0.1 on 2026-02-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_produto_imagem_url_alter_pedido_id_transacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cep_entrega',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazo_entrega',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_frete',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='altura_cm',
            field=models.IntegerField(default=2, help_text='Altura em cm (Min 2)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento_cm',
            field=models.IntegerField(default=15, help_text='Comprimento em cm (Min 15)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura_cm',
            field=models.IntegerField(default=10, help_text='Largura em cm (Min 10)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_g',
            field=models.IntegerField(default=200, help_text='Peso em gramas (ex: 200)'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='alergias',
            field=models.TextField(blank=True, help_text='Se não houver, deixe em branco.', verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='condicao_medica',
            field=models.TextField(blank=True, help_text='Se não houver, deixe em branco.', verbose_name='Condição Médica (Doenças)'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='instrucoes_abordagem',
            field=models.TextField(blank=True, help_text='Ex: Fale baixo, não toque bruscamente.', verbose_name='Como conversar/acalmar?'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='medicamentos',
            field=models.TextField(blank=True, help_text='Se não houver, deixe em branco.', verbose_name='Medicamentos em Uso'),
        ),
        migrations.AlterField(
            model_name='pulseira',
            name='nome_convenio',
            field=models.CharField(blank=True, help_text='Digite o nome (e o número da carteirinha, se quiser).', max_length=100, verbose_name='Nome do Convênio'),
        ),
    ]
