"""
Django settings for projeto_sos project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'chave-padrao-caso-falhe')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projeto_sos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto_sos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTHENTICATION_BACKENDS = [
    'core.auth_backends.CPFOrEmailBackend', # Seu novo login
    'django.contrib.auth.backends.ModelBackend', # Mantém o padrão para o Admin
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# --- CONFIGURAÇÕES REGIONAIS ---

# Idioma para Português do Brasil
LANGUAGE_CODE = 'pt-br'

# Fuso Horário de Brasília
TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True
USE_TZ = True

# Formato de data para DD/MM/AAAA (Input e Display)
DATE_INPUT_FORMATS = ['%d/%m/%Y']
DATETIME_INPUT_FORMATS = ['%d/%m/%Y %H:%M:%S']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Configuração de Arquivos de Mídia (Fotos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuração de Envio de Email Real (GMAIL)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# --- PREENCHA COM SEUS DADOS ---
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')

JAZZMIN_SETTINGS = {
    "site_title": "Sistema SOS",
    "site_header": "Administração SOS",
    "site_brand": "SOS Pulseira",
    "welcome_sign": "Bem-vindo ao Painel de Gestão",
    "copyright": "Sistema SOS Ltd",
    "search_model": "core.Pulseira", # Permite pesquisar pulseiras no topo
}

# Redirecionar para o painel após login com sucesso
LOGIN_REDIRECT_URL = 'dashboard'

# Redirecionar para a página de login após sair
LOGOUT_REDIRECT_URL = 'login'

# Para onde ir se tentar acessar página restrita sem estar logado
LOGIN_URL = 'login'

# Permite que o Django aceite solicitações do seu domínio
ALLOWED_HOSTS = ['jessicagarcia1.pythonanywhere.com']

# Configurações de Segurança para HTTPS (Essencial para PythonAnywhere)
CSRF_TRUSTED_ORIGINS = ['https://jessicagarcia1.pythonanywhere.com']

# Garante que os cookies do CSRF e da Sessão só viajem por HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
